# ruby encoding: utf-8
GameQueue.create(name: 'Not in Game Queue', display: false)
GameQueue.create(name: 'Shorter than 30 Hours', display: true)
GameQueue.create(name: 'Longer than 30 Hours', display: true)
GameConsole.create(name: 'SNES')
GameConsole.create(name: 'Nintendo 64')
GameConsole.create(name: 'Xbox 360')
GameGenre.create(name: 'JRPG')
GameGenre.create(name: 'RTS')
GameGenre.create(name: 'Walking Simulator')
